In [1]:
import pandas as pd

In [3]:
data=pd.read_csv("CKD.csv")
data

,age,bp,sg,al,su,rbc,pc,pcc,ba,bgr,...,pcv,wc,rc,htn,dm,cad,appet,pe,ane,classification
0,2.000000,76.459948,c,3.0,0.0,normal,abnormal,notpresent,notpresent,148.112676,...,38.868902,8408.191126,4.705597,no,no,no,yes,yes,no,yes
1,3.000000,76.459948,c,2.0,0.0,normal,normal,notpresent,notpresent,148.112676,...,34.000000,12300.000000,4.705597,no,no,no,yes,poor,no,yes
2,4.000000,76.459948,a,1.0,0.0,normal,normal,notpresent,notpresent,99.000000,...,34.000000,8408.191126,4.705597,no,no,no,yes,poor,no,yes
3,5.000000,76.459948,d,1.0,0.0,normal,normal,notpresent,notpresent,148.112676,...,38.868902,8408.191126,4.705597,no,no,no,yes,poor,yes,yes
4,5.000000,50.000000,c,0.0,0.0,normal,normal,notpresent,notpresent,148.112676,...,36.000000,12400.000000,4.705597,no,no,no,yes,poor,no,yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
394,51.492308,70.000000,a,0.0,0.0,normal,normal,notpresent,notpresent,219.000000,...,37.000000,9800.000000,4.400000,no,no,no,yes,poor,no,yes
395,51.492308,70.000000,c,0.0,2.0,normal,normal,notpresent,notpresent,220.000000,...,27.000000,8408.191126,4.705597,yes,yes,no,yes,poor,yes,yes
396,51.492308,70.000000,c,3.0,0.0,normal,normal,notpresent,notpresent,110.000000,...,26.000000,9200.000000,3.400000,yes,yes,no,poor,poor,no,yes
397,51.492308,90.000000,a,0.0,0.0,normal,normal,notpresent,notpresent,207.000000,...,38.868902,8408.191126,4.705597,yes,yes,no,yes,poor,yes,yes
398,51.492308,80.000000,a,0.0,0.0,normal,normal,notpresent,notpresent,100.000000,...,53.000000,8500.000000,4.900000,no,no,no,yes,poor,no,no

In [7]:
data=pd.get_dummies(data,drop_first=True)
data

,age,bp,al,su,bgr,bu,sc,sod,pot,hrmo,...,pc_normal,pcc_present,ba_present,htn_yes,dm_yes,cad_yes,appet_yes,pe_yes,ane_yes,classification_yes
0,2.000000,76.459948,3.0,0.0,148.112676,57.482105,3.077356,137.528754,4.627244,12.518156,...,False,False,False,False,False,False,True,True,False,True
1,3.000000,76.459948,2.0,0.0,148.112676,22.000000,0.700000,137.528754,4.627244,10.700000,...,True,False,False,False,False,False,True,False,False,True
2,4.000000,76.459948,1.0,0.0,99.000000,23.000000,0.600000,138.000000,4.400000,12.000000,...,True,False,False,False,False,False,True,False,False,True
3,5.000000,76.459948,1.0,0.0,148.112676,16.000000,0.700000,138.000000,3.200000,8.100000,...,True,False,False,False,False,False,True,False,True,True
4,5.000000,50.000000,0.0,0.0,148.112676,25.000000,0.600000,137.528754,4.627244,11.800000,...,True,False,False,False,False,False,True,False,False,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
394,51.492308,70.000000,0.0,0.0,219.000000,36.000000,1.300000,139.000000,3.700000,12.500000,...,True,False,False,False,False,False,True,False,False,True
395,51.492308,70.000000,0.0,2.0,220.000000,68.000000,2.800000,137.528754,4.627244,8.700000,...,True,False,False,True,True,False,True,False,True,True
396,51.492308,70.000000,3.0,0.0,110.000000,115.000000,6.000000,134.000000,2.700000,9.100000,...,True,False,False,True,True,False,False,False,False,True
397,51.492308,90.000000,0.0,0.0,207.000000,80.000000,6.800000,142.000000,5.500000,8.500000,...,True,False,False,True,True,False,True,False,True,True
398,51.492308,80.000000,0.0,0.0,100.000000,49.000000,1.000000,140.000000,5.000000,16.300000,...,True,False,False,False,False,False,True,False,False,False

In [9]:
data.columns

Index(['age', 'bp', 'al', 'su', 'bgr', 'bu', 'sc', 'sod', 'pot', 'hrmo', 'pcv',
       'wc', 'rc', 'sg_b', 'sg_c', 'sg_d', 'sg_e', 'rbc_normal', 'pc_normal',
       'pcc_present', 'ba_present', 'htn_yes', 'dm_yes', 'cad_yes',
       'appet_yes', 'pe_yes', 'ane_yes', 'classification_yes'],
      dtype='object')

In [11]:
data["classification_yes"].value_counts()

classification_yes
True     249
False    150
Name: count, dtype: int64

In [13]:
independent=data[['age', 'bp', 'al', 'su', 'bgr', 'bu', 'sc', 'sod', 'pot', 'hrmo', 'pcv',
       'wc', 'rc', 'sg_b', 'sg_c', 'sg_d', 'sg_e', 'rbc_normal', 'pc_normal',
       'pcc_present', 'ba_present', 'htn_yes', 'dm_yes', 'cad_yes',
       'appet_yes', 'pe_yes', 'ane_yes']]
dependent=data[["classification_yes"]]

In [15]:
independent.shape

(399, 27)

In [17]:
from sklearn.model_selection import train_test_split
xtrain,xtest,ytrain,ytest=train_test_split(independent,dependent,test_size=0.30,random_state=0)

In [19]:
from sklearn.tree import DecisionTreeClassifier

In [35]:
from sklearn.model_selection import GridSearchCV
param_grid={'criterion':['gini', 'entropy', 'log_loss'],'splitter':['best', 'random']}
grid=GridSearchCV(DecisionTreeClassifier(),param_grid,refit=True,verbose=3,n_jobs=-1,scoring='f1_weighted')
grid.fit(xtrain,ytrain)
re=grid.cv_results_
grid_prediction=grid.predict(xtest)
from sklearn.metrics import confusion_matrix
cm=confusion_matrix(ytest,grid_prediction)
from sklearn.metrics import classification_report
clf_report=classification_report(ytest,grid_prediction)

Fitting 5 folds for each of 6 candidates, totalling 30 fits

In [41]:
from sklearn.metrics import f1_score
f1_macro=f1_score(ytest,grid_prediction,average="weighted")
print("the best f1score is{}:".format(grid.best_params_),f1_macro)

the best f1score is{'criterion': 'gini', 'splitter': 'random'}: 0.9834018801410106

In [43]:
print("The confusion matrix is \n",cm)

The confusion matrix is
 [[45  0]
 [ 2 73]]

In [45]:
print("The classification report is \n",clf_report)

The classification report is
               precision    recall  f1-score   support

       False       0.96      1.00      0.98        45
        True       1.00      0.97      0.99        75

    accuracy                           0.98       120
   macro avg       0.98      0.99      0.98       120
weighted avg       0.98      0.98      0.98       120

In [51]:
from sklearn.metrics import roc_auc_score
roc_auc_score(ytest,grid.predict_proba(xtest)[:,1])

0.9866666666666667

In [55]:
table=pd.DataFrame.from_dict(re)
table

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_criterion,param_splitter,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.006428,0.005338,0.014851,0.003447,gini,best,"{'criterion': 'gini', 'splitter': 'best'}",0.929144,0.926743,0.894531,0.926743,0.963636,0.928159,0.021884,6
1,0.006686,0.003290,0.013237,0.000965,gini,random,"{'criterion': 'gini', 'splitter': 'random'}",0.982221,0.982051,0.929144,0.946663,0.981894,0.964395,0.022328,1
2,0.005622,0.000609,0.011118,0.001862,entropy,best,"{'criterion': 'entropy', 'splitter': 'best'}",1.000000,0.945469,0.859355,0.909115,0.963636,0.935515,0.048053,5
3,0.010936,0.002964,0.012234,0.001844,entropy,random,"{'criterion': 'entropy', 'splitter': 'random'}",1.000000,0.946153,0.929144,0.964286,0.981894,0.964295,0.025097,3
4,0.005793,0.000677,0.012682,0.001287,log_loss,best,"{'criterion': 'log_loss', 'splitter': 'best'}",1.000000,0.945469,0.876984,0.909115,0.981728,0.942659,0.045301,4
5,0.004992,0.000551,0.009686,0.001163,log_loss,random,"{'criterion': 'log_loss', 'splitter': 'random'}",1.000000,0.982221,0.947015,0.946663,0.946014,0.964383,0.022538,2

In [59]:
best=grid.best_score_
best

0.9643947069544134